import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "../layout/header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header
        logoSrc={"/assets/logoblack.png"}
        navLinks={[
          { label: "Home", href: "/" },
          {
            label: "About",
            href: "/about",
            dropdown: [
              { label: "Team", href: "/about/team" },
              { label: "Company", href: "/about/company" },
            ],
          },
          {
            label: "Services",
            href: "/services",
            dropdown: [
              { label: "Consulting", href: "/services/consulting" },
              { label: "Development", href: "/services/development" },
            ],
          },
          { label: "Contact", href: "/contact" },
          { label: "Contact", href: "/contact" },
          { label: "Contact", href: "/contact" },
          { label: "Cart", href: "/contact" },
        ]}
      />
        {children}</body>
    </html>
  );
}
